### ISSUE TITLE
Question about gOBJ

### ISSUE THREAD

**Issue by baoyufuyou** [castetsb/pyRobotiqGripper#1]
Thank you for your share of pyRobotiqGripper.
Can i ask a question about function goTo():, In this function there is object detection.
But when i run it, it always show me gOBJ=3.
Can you tell me possible reasons?  
('gripperStatusReg0', '11111001')
('faultStatusReg2', '11100110')
('posRequestEchoReg3', '00000000')
('positionReg4', '00000000')
('currentReg5', '00000000')
Thanks a lot
Best,
Lei

**Comment by castetsb** [comment]
I did some update of the code. There was several mistakes. You can give it another try now.

**Comment by castetsb** [comment]
I close this question because it is outdated but your are welcome to renew it if necessary.
