### ISSUE TITLE
Activation did not complete without timeout

### ISSUE THREAD

**Issue by arthur801031** [castetsb/pyRobotiqGripper#3]
Hi,

I'm using a CB2 UR5 with Robotiq 2F-85 grippers. I tried `grip.resetActivate()` and saw the grippers opened and closed, and the program timed out in the `activate` function and received this error: `Exception: Activation did not complete without timeout`. I checked the `gSTA` value, and it's all 0s before the timeout. Do you know what might be causing this issue?

Thank you.

**Comment by castetsb** [comment]
Thank you for communicating this issue.
Could you try again with the latest version of the program ? I made some change on this recently.
Documentation have also been updated and it is now possible to install the pyRobotiqGripper package using PIP.
